package com.appathy.manabutalk

/** 用語辞典。SC頻出の略語(正式名称・語源つき)と分野別用語を収録。 */
object Glossary {
    data class Term(
        val term: String,
        val reading: String,
        val full: String,      // 正式名称(なければ空)
        val desc: String,      // 意味
        val etym: String,      // 語源(なければ空)
        val cat: String        // 分野
    )

    val categories = listOf(
        "暗号・認証", "ネットワーク", "Web・アプリ", "メール", "マルウェア・攻撃", "セキュリティ運用・管理", "クラウド・システム", "その他"
    )

    val terms: List<Term> = listOf(
        Term("AES", "", "Advanced Encryption Standard", "現在の標準的な共通鍵ブロック暗号。", "Advanced=高度な / Encryption=暗号化 / Standard=標準", "暗号・認証"),
        Term("CA", "", "Certificate Authority", "デジタル証明書を発行する認証局。", "Certificate=証明書 / Authority=認証機関", "暗号・認証"),
        Term("CRL", "", "Certificate Revocation List", "有効期限内に失効した証明書のシリアル番号を記載する失効リスト。", "", "暗号・認証"),
        Term("FIDO/パスキー", "", "Fast IDentity Online", "生体情報などを端末内で照合し、外部に送らない公開鍵ベースの認証。", "", "暗号・認証"),
        Term("HMAC", "", "Hash-based Message Authentication Code", "ハッシュ関数と共通鍵で作るメッセージ認証符号。改ざん検知に使う。", "Hash=ハッシュ / Authentication=認証 / Code=符号", "暗号・認証"),
        Term("IEEE 802.1X", "", "", "EAPを用いたポートベース認証の枠組み。サプリカント/オーセンティケータ/認証サーバで構成。", "", "暗号・認証"),
        Term("LDAP", "", "Lightweight Directory Access Protocol", "利用者や資源の情報(ディレクトリ)へアクセスするプロトコル。", "Lightweight=軽量 / Directory=名簿 / Access=アクセス", "暗号・認証"),
        Term("MFA", "", "Multi-Factor Authentication", "知識・所持・生体など複数要素を組み合わせる多要素認証。", "Multi=複数 / Factor=要素", "暗号・認証"),
        Term("OCSP", "", "Online Certificate Status Protocol", "証明書の失効状態をオンラインで問い合わせるプロトコル。VAが応答する。", "", "暗号・認証"),
        Term("PKI", "", "Public Key Infrastructure", "公開鍵暗号と証明書で信頼を担保する基盤。CA/RA/VAで構成。", "Public=公開 / Key=鍵 / Infrastructure=基盤", "暗号・認証"),
        Term("PQC", "", "Post-Quantum Cryptography", "耐量子計算機暗号。量子コンピュータの攻撃にも耐える暗号方式。", "", "暗号・認証"),
        Term("RADIUS", "", "Remote Authentication Dial-In User Service", "認証・認可・課金(AAA)を集中管理する認証サーバのプロトコル。", "Remote=遠隔 / Dial-In=外部接続", "暗号・認証"),
        Term("RSA", "", "Rivest–Shamir–Adleman", "代表的な公開鍵暗号方式。大きな数の素因数分解の困難性に基づく。", "発明者3人の頭文字(Rivest, Shamir, Adleman)", "暗号・認証"),
        Term("SHA", "", "Secure Hash Algorithm", "代表的なハッシュ関数群。SHA-256などが使われる。", "Algorithm=アルゴリズム(語源は数学者アル＝フワーリズミー)", "暗号・認証"),
        Term("SSL", "", "Secure Sockets Layer", "TLSの前身の暗号化プロトコル(現在は非推奨)。", "Socket=接続口 / Layer=層", "暗号・認証"),
        Term("TLS", "", "Transport Layer Security", "通信を暗号化するプロトコル。TLS1.3が最新。", "Transport=転送", "暗号・認証"),
        Term("サンドボックス", "", "", "隔離された実行環境。不審なプログラムを安全に動かし挙動を観察する。", "", "暗号・認証"),
        Term("ストレッチング", "", "", "ハッシュ計算を繰り返し、解読を困難にする手法。", "", "暗号・認証"),
        Term("ソルト", "", "", "ハッシュ化の前に加える乱数。同一パスワードの同一ハッシュ化を防ぐ。", "", "暗号・認証"),
        Term("チャレンジレスポンス", "", "", "毎回異なる乱数(チャレンジ)を用いてパスワードを送らずに認証する方式。", "", "暗号・認証"),
        Term("デジタル署名", "", "", "秘密鍵で署名し公開鍵で検証する電子的な署名。真正性・完全性を担保。", "", "暗号・認証"),
        Term("ハッシュ", "", "", "データから固定長の要約値を得る一方向関数の結果。", "", "暗号・認証"),
        Term("パスフレーズ", "", "", "複数語からなる長い認証用文字列。", "", "暗号・認証"),
        Term("ワンタイムパスワード", "", "", "一度だけ使える使い捨てのパスワード。", "", "暗号・認証"),
        Term("ワンタイムパッド", "", "", "使い捨ての乱数鍵を用い、情報理論的安全性を持つ暗号。", "", "暗号・認証"),
        Term("ARP", "", "Address Resolution Protocol", "IPアドレスからMACアドレスを求める同一LAN内のプロトコル。", "Address=アドレス / Resolution=対応付け / Protocol=通信規約", "ネットワーク"),
        Term("DHCP", "", "Dynamic Host Configuration Protocol", "IPアドレス等を自動で割り当てるプロトコル。", "Dynamic=動的 / Host=ホスト / Configuration=設定", "ネットワーク"),
        Term("DMZ", "", "DeMilitarized Zone", "外部と内部の境界に置く緩衝ネットワーク。公開サーバを設置する。", "", "ネットワーク"),
        Term("DNS", "", "Domain Name System", "ドメイン名とIPアドレスを対応付ける仕組み。", "Domain=領域 / Name=名前 / System=仕組み", "ネットワーク"),
        Term("DNSSEC", "", "DNS Security Extensions", "DNS応答に署名を付け、出所と完全性を検証する拡張。", "Security=安全 / Extensions=拡張機能", "ネットワーク"),
        Term("DTLS", "", "Datagram TLS", "UDP上でパケット単位に暗号化を行うTLS。", "", "ネットワーク"),
        Term("FTP", "", "File Transfer Protocol", "ファイルを転送するプロトコル(平文)。", "File=ファイル / Transfer=転送", "ネットワーク"),
        Term("ICMP", "", "Internet Control Message Protocol", "到達性確認やエラー通知を行うIP層の制御メッセージ。pingで使う。", "Control=制御 / Message=メッセージ", "ネットワーク"),
        Term("IP", "", "Internet Protocol", "インターネットの基盤となるネットワーク層プロトコル。", "Internet=インターネット / Protocol=通信規約", "ネットワーク"),
        Term("IPsec", "", "Internet Protocol Security", "ネットワーク層で暗号化・認証を行うVPNプロトコル。", "Security=セキュリティ", "ネットワーク"),
        Term("IPv4", "", "Internet Protocol Version 4", "32ビットのアドレスを使うIP。", "Version=版", "ネットワーク"),
        Term("IPv6", "", "Internet Protocol Version 6", "128ビットのアドレスを使うIP。アドレス枯渇に対応。", "Version=版", "ネットワーク"),
        Term("LAN", "", "Local Area Network", "構内など狭い範囲のネットワーク。", "Local=地域 / Area=範囲 / Network=通信網", "ネットワーク"),
        Term("NAT", "", "Network Address Translation", "プライベートIPとグローバルIPを相互変換する。", "Translation=変換", "ネットワーク"),
        Term("NTP", "", "Network Time Protocol", "機器の時刻を同期させるプロトコル。", "Time=時刻", "ネットワーク"),
        Term("SNMP", "", "Simple Network Management Protocol", "ネットワーク機器を監視・管理するプロトコル。", "Management=管理", "ネットワーク"),
        Term("SSH", "", "Secure Shell", "通信を暗号化して遠隔ログインするプロトコル。", "Shell=OSとの対話環境", "ネットワーク"),
        Term("TCP", "", "Transmission Control Protocol", "再送制御などで信頼性を確保するコネクション型トランスポート。", "Transmission=伝送 / Control=制御", "ネットワーク"),
        Term("UDP", "", "User Datagram Protocol", "コネクションレスで高速なトランスポート。", "Datagram=データ報", "ネットワーク"),
        Term("VPN", "", "Virtual Private Network", "公衆網上に仮想的な専用線を作る技術。", "Virtual=仮想の / Private=専用の", "ネットワーク"),
        Term("WAN", "", "Wide Area Network", "地理的に広い範囲を結ぶネットワーク。", "Wide=広域", "ネットワーク"),
        Term("スニッフィング", "", "", "ネットワーク上の通信を盗聴すること。", "", "ネットワーク"),
        Term("トンネリング", "", "", "ある通信を別のプロトコルで包んで転送する技術。", "", "ネットワーク"),
        Term("ハニーポット", "", "", "攻撃者を誘い込み手口を観察するおとりのシステム。", "", "ネットワーク"),
        Term("バックドア", "", "", "不正侵入用に仕込まれた裏口。", "", "ネットワーク"),
        Term("ファイアウォール", "", "", "通信を制御して不正な通信を遮断する仕組み・装置。", "", "ネットワーク"),
        Term("フラッディング", "", "", "大量の通信を送りつけて機能を妨害する攻撃。", "", "ネットワーク"),
        Term("プロキシ", "", "", "通信を中継するサーバ。", "", "ネットワーク"),
        Term("ポートスキャン", "", "", "開いているポートを調べて侵入口を探る偵察行為。", "", "ネットワーク"),
        Term("ロードバランサ", "", "", "負荷を複数サーバへ分散させる装置。", "", "ネットワーク"),
        Term("HTTP", "", "HyperText Transfer Protocol", "Webページをやり取りする通信プロトコル。", "HyperText=ハイパーテキスト / Transfer=転送", "Web・アプリ"),
        Term("HTTPS", "", "HyperText Transfer Protocol Secure", "HTTPをTLSで暗号化した安全な通信。", "Secure=安全な", "Web・アプリ"),
        Term("OAuth 2.0", "", "", "リソースオーナーの許可の下、クライアントにアクセス権限を付与する認可の仕組み。", "", "Web・アプリ"),
        Term("OSコマンドインジェクション", "", "", "入力でOSコマンドを実行させる攻撃。対策はシェル起動を避ける。", "", "Web・アプリ"),
        Term("REST", "", "Representational State Transfer", "HTTPを素直に使うWeb API設計様式。", "Representation=表現 / State=状態 / Transfer=移動", "Web・アプリ"),
        Term("SAML", "", "Security Assertion Markup Language", "ドメイン間で認証情報を交換しSSOを実現するXMLベースの標準。", "Assertion=表明 / Markup=マークアップ", "Web・アプリ"),
        Term("SQLインジェクション", "", "", "入力でSQL文を改ざんし不正実行させる攻撃。対策はプレースホルダ。", "", "Web・アプリ"),
        Term("URL", "", "Uniform Resource Locator", "Web上の資源の場所を示すアドレス。", "Uniform=統一された / Resource=資源 / Locator=場所を示すもの", "Web・アプリ"),
        Term("WAF", "", "Web Application Firewall", "Webアプリへの攻撃を検査して遮断する。", "Firewall=防火壁", "Web・アプリ"),
        Term("XSS", "", "Cross-Site Scripting", "Webページに不正なスクリプトを埋め込む攻撃。対策は出力のエスケープ。", "Cross=横断 / Site=サイト / Scripting=スクリプト実行", "Web・アプリ"),
        Term("クリックジャッキング", "", "", "透明な要素を重ね誤クリックさせる攻撃。対策はX-Frame-Options。", "", "Web・アプリ"),
        Term("クロスサイトスクリプティング", "", "", "Webページに不正スクリプトを実行させる攻撃(XSS)。", "", "Web・アプリ"),
        Term("クロスサイトリクエストフォージェリ", "", "", "利用者になりすまして意図しない処理を実行させる攻撃(CSRF)。", "", "Web・アプリ"),
        Term("セッションハイジャック", "", "", "セッションIDを奪い利用者になりすます攻撃。", "", "Web・アプリ"),
        Term("セッションフィクセーション", "", "", "攻撃者が用意したセッションIDを使わせる攻撃。", "", "Web・アプリ"),
        Term("ディレクトリトラバーサル", "", "", "パスを遡って非公開ファイルへ不正アクセスする攻撃。", "", "Web・アプリ"),
        Term("バッファオーバーフロー", "", "", "確保領域を超える書き込みでメモリを溢れさせ悪用する攻撃。", "", "Web・アプリ"),
        Term("DKIM", "", "DomainKeys Identified Mail", "電子メールに署名を付け、受信側が公開鍵で検証する送信ドメイン認証。", "", "メール"),
        Term("DMARC", "", "Domain-based Message Authentication, Reporting and Conformance", "SPF/DKIMの認証失敗時の処理方針を送信側が宣言する仕組み。", "", "メール"),
        Term("OP25B", "", "Outbound Port 25 Blocking", "ISP管理下から外部への25番ポート直送信を遮断し、迷惑メールを制限する。", "", "メール"),
        Term("POP3", "", "Post Office Protocol Version 3", "メールを受信するプロトコル。", "Post Office=郵便局(メール受信を郵便に例えた名称)", "メール"),
        Term("SMTP", "", "Simple Mail Transfer Protocol", "メールを送信するプロトコル。", "Simple=簡単な / Mail=電子メール", "メール"),
        Term("SPF", "", "Sender Policy Framework", "送信元IPアドレスから送信ドメインの正当性を検証する送信ドメイン認証。", "", "メール"),
        Term("DDoS", "", "Distributed Denial of Service", "多数の端末から一斉に負荷をかけて停止させる分散型サービス妨害攻撃。", "Distributed=分散した / Denial=拒否 / Service=サービス", "マルウェア・攻撃"),
        Term("DNSキャッシュポイズニング", "", "", "偽のDNS応答をキャッシュさせる攻撃。対策は問合せIDと送信元ポートのランダム化。", "", "マルウェア・攻撃"),
        Term("DRDoS", "", "Distributed Reflection DoS", "送信元を標的に偽装したリクエストを多数のサーバへ送り、応答を標的に集中させる反射・増幅型DoS。", "", "マルウェア・攻撃"),
        Term("Mirai", "", "", "IoT機器に感染してボットネットを構成し、C&Cの指令でDDoSを行うマルウェア。", "", "マルウェア・攻撃"),
        Term("MITB", "", "Man in the Browser", "ブラウザを乗っ取り取引内容を改ざんする攻撃。対策にトランザクション署名。", "", "マルウェア・攻撃"),
        Term("Pass the Hash", "", "", "盗んだパスワードのハッシュ値をそのまま提示して認証を通す攻撃。", "", "マルウェア・攻撃"),
        Term("ウイルス", "", "", "他のプログラムに寄生して自己増殖する不正プログラム。", "", "マルウェア・攻撃"),
        Term("クリプトジャッキング", "", "", "他人のPC資源を無断で使い暗号資産のマイニングを行う攻撃。", "", "マルウェア・攻撃"),
        Term("サイドチャネル攻撃", "", "", "処理時間や消費電力など物理的な副次情報から秘密情報を推定する攻撃。", "", "マルウェア・攻撃"),
        Term("サイバーキルチェーン", "", "", "偵察→武器化→デリバリー→エクスプロイト→インストール→C&C→目的実行と攻撃段階をモデル化。", "", "マルウェア・攻撃"),
        Term("サプライチェーン攻撃", "", "", "取引先や委託先を経由して侵入する攻撃。", "", "マルウェア・攻撃"),
        Term("スパイウェア", "", "", "気付かれずに情報を盗み出すソフトウェア。", "", "マルウェア・攻撃"),
        Term("スプーフィング", "", "", "送信元などを偽装するなりすまし攻撃。", "", "マルウェア・攻撃"),
        Term("スミッシング", "", "", "SMSを利用したフィッシング。", "", "マルウェア・攻撃"),
        Term("ゼロデイ攻撃", "", "", "修正が提供される前の脆弱性を狙う攻撃。", "", "マルウェア・攻撃"),
        Term("ディープフェイク", "", "", "AIで生成・加工した本物そっくりの音声・映像。なりすまし詐欺などに悪用。", "", "マルウェア・攻撃"),
        Term("トロイの木馬", "", "", "正常なソフトを装って侵入する不正プログラム。", "", "マルウェア・攻撃"),
        Term("ドメインフロンティング", "", "", "CDN等でSNIと実際のHostを食い違わせ、正規ドメインに見せかけて実通信先を隠す手法。", "", "マルウェア・攻撃"),
        Term("パスワードリスト攻撃", "", "", "他所から流出したID・パスワードで不正ログインを試す攻撃。", "", "マルウェア・攻撃"),
        Term("ビッシング", "", "", "音声電話を利用した詐欺(ボイスフィッシング)。", "", "マルウェア・攻撃"),
        Term("フィッシング", "", "", "偽サイトへ誘導して情報を盗む攻撃。", "", "マルウェア・攻撃"),
        Term("ブルートフォース攻撃", "", "", "考えられる全ての組合せを試す総当たり攻撃。", "", "マルウェア・攻撃"),
        Term("ボット", "", "", "遠隔操作される感染端末。", "", "マルウェア・攻撃"),
        Term("ボットネット", "", "", "ボット化した端末を多数束ねたネットワーク。", "", "マルウェア・攻撃"),
        Term("マルウェア", "", "", "悪意のあるソフトウェアの総称。", "", "マルウェア・攻撃"),
        Term("ランサムウェア", "", "", "ファイルを暗号化し身代金を要求するマルウェア。", "", "マルウェア・攻撃"),
        Term("リプレイ攻撃", "", "", "盗んだ通信内容をそのまま再送してなりすます攻撃。", "", "マルウェア・攻撃"),
        Term("ワーム", "", "", "単独で自己増殖して感染を広げるマルウェア。", "", "マルウェア・攻撃"),
        Term("中間者攻撃", "", "", "通信の途中に割り込み盗聴・改ざんする攻撃(MITM)。", "", "マルウェア・攻撃"),
        Term("標的型攻撃", "", "", "特定の組織を狙って執拗に行う攻撃。", "", "マルウェア・攻撃"),
        Term("CPE", "", "Common Platform Enumeration", "製品やプラットフォームを識別する共通の名称体系。", "", "セキュリティ運用・管理"),
        Term("CSIRT", "", "Computer Security Incident Response Team", "組織のセキュリティ事故に対応する専門チーム。", "Incident=事故 / Response=対応 / Team=チーム", "セキュリティ運用・管理"),
        Term("CVE", "", "Common Vulnerabilities and Exposures", "個別の脆弱性に一意の識別番号を付与する共通脆弱性識別子。MITREが採番。", "", "セキュリティ運用・管理"),
        Term("CVSS", "", "Common Vulnerability Scoring System", "脆弱性の深刻度を数値評価する共通基準。", "", "セキュリティ運用・管理"),
        Term("CWE", "", "Common Weakness Enumeration", "脆弱性の種類(弱点)を分類・列挙した共通基準。", "", "セキュリティ運用・管理"),
        Term("EDR", "", "Endpoint Detection and Response", "端末の挙動を監視し、侵入後の不審な動きを検知・対応する仕組み。", "", "セキュリティ運用・管理"),
        Term("IDS", "", "Intrusion Detection System", "不正侵入を検知して通知する仕組み。", "Intrusion=侵入 / Detection=検知", "セキュリティ運用・管理"),
        Term("IoC", "", "Indicator of Compromise", "侵害の痕跡。C&C通信履歴や不審なハッシュ値など。", "", "セキュリティ運用・管理"),
        Term("IPS", "", "Intrusion Prevention System", "不正侵入を検知し、遮断まで行う仕組み。", "Prevention=防止", "セキュリティ運用・管理"),
        Term("ISMAP", "", "Information system Security Management and Assessment Program", "政府調達向けにクラウドのセキュリティを事前評価・登録する制度。", "", "セキュリティ運用・管理"),
        Term("JIS Q 27000", "", "", "ISMSの用語規格。機密性・完全性・可用性・真正性・信頼性などを定義。", "", "セキュリティ運用・管理"),
        Term("MITRE ATT&CK", "", "", "攻撃者の戦術・技術を体系化したナレッジベース。", "", "セキュリティ運用・管理"),
        Term("NIST CSF", "", "Cybersecurity Framework", "重要インフラのセキュリティ改善枠組み。2.0でGOVERNを含む6機能。", "", "セキュリティ運用・管理"),
        Term("PSIRT", "", "Product Security Incident Response Team", "自社製品の脆弱性に起因するリスクへ対応する組織。", "", "セキュリティ運用・管理"),
        Term("SBOM", "", "Software Bill of Materials", "ソフトウェアの構成部品と依存関係の一覧。含まれる部品の脆弱性管理に使う。", "", "セキュリティ運用・管理"),
        Term("SIEM", "", "Security Information and Event Management", "各種機器のログを集約・相関分析して脅威を検知する仕組み。", "Event=出来事 / Management=管理", "セキュリティ運用・管理"),
        Term("SOAR", "", "Security Orchestration, Automation and Response", "脅威情報の活用と運用自動化で対応を効率化する技術。", "", "セキュリティ運用・管理"),
        Term("SOC", "", "Security Operation Center", "ログ監視や脅威検知を継続的に行う組織・機能。", "", "セキュリティ運用・管理"),
        Term("UEBA", "", "User and Entity Behavior Analytics", "利用者や機器の行動を分析し、異常な振る舞いを検知する仕組み。", "", "セキュリティ運用・管理"),
        Term("インシデント", "", "", "セキュリティ上の事故・望ましくない出来事。", "", "セキュリティ運用・管理"),
        Term("ガイドライン", "", "", "具体的な運用の指針。", "", "セキュリティ運用・管理"),
        Term("コンプライアンス", "", "", "法令や規範の遵守。", "", "セキュリティ運用・管理"),
        Term("セキュリティポリシー", "", "", "組織の情報セキュリティ基本方針。", "", "セキュリティ運用・管理"),
        Term("ゼロトラスト", "", "", "全ての利用者・機器・接続を信頼せず、都度アクセスの正当性を検証する考え方。", "", "セキュリティ運用・管理"),
        Term("バックアップ", "", "", "データを別に複製して保全すること。", "", "セキュリティ運用・管理"),
        Term("パッチ", "", "", "脆弱性などを修正するプログラム。", "", "セキュリティ運用・管理"),
        Term("フォレンジックス", "", "", "不正の証拠を保全・解析するデジタル鑑識。", "", "セキュリティ運用・管理"),
        Term("ベンダ", "", "", "製品を提供する会社。", "", "セキュリティ運用・管理"),
        Term("ベンチマーク", "", "", "性能などを比較するための基準。", "", "セキュリティ運用・管理"),
        Term("ペネトレーションテスト", "", "", "実際に攻撃を試みて侵入可否を検証する疑似攻撃試験。", "", "セキュリティ運用・管理"),
        Term("リスクアセスメント", "", "", "リスクを洗い出し評価すること。", "", "セキュリティ運用・管理"),
        Term("ログ", "", "", "操作や通信の記録。追跡や監査に用いる。", "", "セキュリティ運用・管理"),
        Term("CASB", "", "Cloud Access Security Broker", "クラウド利用を可視化・制御し、シャドーITの検出などを行う仕組み。", "", "クラウド・システム"),
        Term("CSPM", "", "Cloud Security Posture Management", "クラウドの設定を継続監視し、設定ミスを検知する仕組み。", "", "クラウド・システム"),
        Term("オーケストレーション", "", "", "複数のシステムやコンテナを自動で管理・連携させること。", "", "クラウド・システム"),
        Term("クラウド", "", "", "インターネット経由で利用するサービス形態。", "", "クラウド・システム"),
        Term("コンテナ", "", "", "OSを共有して動く軽量な仮想実行環境。", "", "クラウド・システム"),
        Term("スケーリング", "", "", "負荷に応じて処理能力を拡張・縮小すること。", "", "クラウド・システム"),
        Term("ハイパーバイザ", "", "", "物理マシン上で複数の仮想マシンを動かす仮想化ソフトウェア。", "", "クラウド・システム"),
        Term("フェイルオーバー", "", "", "障害時に待機系へ自動で切り替えること。", "", "クラウド・システム"),
        Term("フェイルバック", "", "", "復旧後に元の系へ戻すこと。", "", "クラウド・システム"),
        Term("マイグレーション", "", "", "システムやデータを別環境へ移行すること。", "", "クラウド・システム"),
        Term("レプリケーション", "", "", "データを別の場所に複製して同期すること。", "", "クラウド・システム"),
        Term("API", "", "Application Programming Interface", "ソフト同士が機能をやり取りするための接点・窓口。", "Application=応用ソフト / Programming=プログラム作成 / Interface=接点・窓口", "その他"),
        Term("RFC", "", "Request for Comments", "インターネット技術の標準仕様をまとめた文書。", "Request=依頼 / Comments=意見", "その他"),
        Term("SQL", "", "Structured Query Language", "リレーショナルデータベースを操作する言語。", "Structured=構造化された / Query=問い合わせ", "その他"),
        Term("XML", "", "eXtensible Markup Language", "データ構造をタグで記述する拡張可能なマークアップ言語。", "eXtensible=拡張可能な / Markup=タグ付け", "その他")
    )
}
